Algoritmo "maior_ou_menor "
// 
//
//  leia 10 numeros e mostre o maior e o menor.
Var
// Seção de Declarações das variáveis 
    i, contador, numero :inteiro

Inicio

      para i de 1 ate 10 faca
      escreva ("Digite um numero: ")
      leia (numero)

      se (numero < contador) entao
      contador <- numero

      fimse
      fimpara
      
      escreva (contador)

      


Fimalgoritmo