Algoritmo "numero_impares "
//  
//  
// 
//  numero impares - mostre os impares de 1 ate N
Var

   numero : inteiro


Inicio

    escreva ("     Numero impares - mostre os impares de 1 ate N")
  escreval("")

 escreva("Digite um numero inteiro: ")
 leia (numero)

para numero de 1 ate numero faca
     se ((numero + 1) % 2 = 0) entao
     escreva (numero)

     senao
     escreva("")

     fimse
 fimpara



Fimalgoritmo